/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'Applied' : null } |
  { 'Rejected' : null } |
  { 'Accepted' : null };
export interface ConnRequest {
  'id' : bigint,
  'to' : Principal,
  'status' : ConnStatus,
  'from' : Principal,
  'createdAt' : bigint,
}
export type ConnStatus = { 'Accepted' : null } |
  { 'Declined' : null } |
  { 'Pending' : null };
export interface ConversationPreview {
  'lastMessageAt' : bigint,
  'lastMessage' : string,
  'unreadCount' : bigint,
  'partner' : Principal,
}
export interface EducationEntry {
  'field' : string,
  'school' : string,
  'year' : string,
  'degree' : string,
}
export interface Endorsement {
  'createdAt' : bigint,
  'skill' : string,
  'endorserPrincipal' : Principal,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface Group {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'memberCount' : bigint,
  'description' : string,
  'creatorPrincipal' : Principal,
  'industry' : string,
}
export interface GroupPost {
  'id' : bigint,
  'postType' : PostType,
  'likeCount' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'groupId' : bigint,
  'authorPrincipal' : Principal,
}
export interface JobApplication {
  'id' : bigint,
  'status' : ApplicationStatus,
  'resume' : [] | [ExternalBlob],
  'applicantPrincipal' : Principal,
  'createdAt' : bigint,
  'jobId' : bigint,
  'coverLetter' : string,
}
export interface JobPosting {
  'id' : bigint,
  'experienceLevel' : string,
  'title' : string,
  'active' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'company' : string,
  'salaryRange' : string,
  'requirements' : string,
  'posterPrincipal' : Principal,
  'location' : string,
  'industry' : string,
}
export interface Message {
  'id' : bigint,
  'to' : Principal,
  'body' : string,
  'from' : Principal,
  'createdAt' : bigint,
  'read' : boolean,
  'attachmentName' : [] | [string],
  'attachment' : [] | [ExternalBlob],
}
export type NotifKind = { 'PostCommented' : null } |
  { 'ConnectionAccepted' : null } |
  { 'JobApplicationReceived' : null } |
  { 'SkillEndorsed' : null } |
  { 'ConnectionRequest' : null } |
  { 'NewMessage' : null } |
  { 'PostLiked' : null } |
  { 'GroupPostCreated' : null };
export interface Notification {
  'id' : bigint,
  'kind' : NotifKind,
  'createdAt' : bigint,
  'read' : boolean,
  'referenceId' : bigint,
  'message' : string,
  'recipientPrincipal' : Principal,
}
export interface PostComment {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'authorPrincipal' : Principal,
  'postId' : bigint,
}
export type PostType = { 'Question' : null } |
  { 'Article' : null } |
  { 'Insight' : null };
export interface Profile {
  'bio' : string,
  'resume' : [] | [ExternalBlob],
  'profileVisibility' : ProfileVisibility,
  'headline' : string,
  'name' : string,
  'createdAt' : bigint,
  'education' : Array<EducationEntry>,
  'workHistory' : Array<WorkEntry>,
  'skills' : Array<string>,
  'location' : string,
  'industry' : string,
  'avatar' : [] | [ExternalBlob],
}
export type ProfileVisibility = { 'ConnectionsOnly' : null } |
  { 'Public' : null };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : Principal,
  'headline' : string,
  'name' : string,
  'avatar' : [] | [ExternalBlob],
}
export interface WorkEntry {
  'startYear' : string,
  'title' : string,
  'endYear' : string,
  'description' : string,
  'company' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addEndorsement' : ActorMethod<[Principal, string], undefined>,
  'applyToJob' : ActorMethod<[bigint, string, [] | [ExternalBlob]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createGroup' : ActorMethod<[string, string, string], bigint>,
  'createJob' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    bigint
  >,
  'createPost' : ActorMethod<[bigint, string, PostType], bigint>,
  'deactivateJob' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<JobApplication>>,
  'getBlockedUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<PostComment>>,
  'getConnectionRequests' : ActorMethod<[], Array<ConnRequest>>,
  'getConnectionSuggestions' : ActorMethod<[], Array<UserSummary>>,
  'getConnections' : ActorMethod<[], Array<Principal>>,
  'getConversations' : ActorMethod<[], Array<ConversationPreview>>,
  'getEndorsements' : ActorMethod<[Principal], Array<Endorsement>>,
  'getFeedPosts' : ActorMethod<[bigint], Array<GroupPost>>,
  'getGroupPosts' : ActorMethod<[bigint], Array<GroupPost>>,
  'getGroups' : ActorMethod<[], Array<Group>>,
  'getJob' : ActorMethod<[bigint], [] | [JobPosting]>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getMyApplications' : ActorMethod<[], Array<JobApplication>>,
  'getMyGroups' : ActorMethod<[], Array<Group>>,
  'getMyJobs' : ActorMethod<[], Array<JobPosting>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getPublicProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getSentRequests' : ActorMethod<[], Array<ConnRequest>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationsCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[bigint], undefined>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'markMessagesRead' : ActorMethod<[Principal], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'removeConnection' : ActorMethod<[Principal], undefined>,
  'respondToRequest' : ActorMethod<[bigint, boolean], undefined>,
  'searchJobs' : ActorMethod<
    [string, string, string, string],
    Array<JobPosting>
  >,
  'searchUsers' : ActorMethod<[string], Array<UserSummary>>,
  'sendConnectionRequest' : ActorMethod<[Principal], bigint>,
  'sendMessage' : ActorMethod<
    [Principal, string, [] | [ExternalBlob], [] | [string]],
    bigint
  >,
  'setAvatar' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'setProfile' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      Array<WorkEntry>,
      Array<EducationEntry>,
    ],
    undefined
  >,
  'setResume' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'toggleLike' : ActorMethod<[bigint], boolean>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, string],
    undefined
  >,
  'updatePrivacySettings' : ActorMethod<[ProfileVisibility], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];