/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostType = IDL.Variant({
  'Question' : IDL.Null,
  'Article' : IDL.Null,
  'Insight' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'Applied' : IDL.Null,
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'resume' : IDL.Opt(ExternalBlob),
  'applicantPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
});
export const PostComment = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorPrincipal' : IDL.Principal,
  'postId' : IDL.Nat,
});
export const ConnStatus = IDL.Variant({
  'Accepted' : IDL.Null,
  'Declined' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ConnRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : ConnStatus,
  'from' : IDL.Principal,
  'createdAt' : IDL.Int,
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Principal,
  'headline' : IDL.Text,
  'name' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const ConversationPreview = IDL.Record({
  'lastMessageAt' : IDL.Int,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
  'partner' : IDL.Principal,
});
export const Endorsement = IDL.Record({
  'createdAt' : IDL.Int,
  'skill' : IDL.Text,
  'endorserPrincipal' : IDL.Principal,
});
export const GroupPost = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'likeCount' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'groupId' : IDL.Nat,
  'authorPrincipal' : IDL.Principal,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'creatorPrincipal' : IDL.Principal,
  'industry' : IDL.Text,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'experienceLevel' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requirements' : IDL.Text,
  'posterPrincipal' : IDL.Principal,
  'location' : IDL.Text,
  'industry' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'body' : IDL.Text,
  'from' : IDL.Principal,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'attachmentName' : IDL.Opt(IDL.Text),
  'attachment' : IDL.Opt(ExternalBlob),
});
export const NotifKind = IDL.Variant({
  'PostCommented' : IDL.Null,
  'ConnectionAccepted' : IDL.Null,
  'JobApplicationReceived' : IDL.Null,
  'SkillEndorsed' : IDL.Null,
  'ConnectionRequest' : IDL.Null,
  'NewMessage' : IDL.Null,
  'PostLiked' : IDL.Null,
  'GroupPostCreated' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'kind' : NotifKind,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'referenceId' : IDL.Nat,
  'message' : IDL.Text,
  'recipientPrincipal' : IDL.Principal,
});
export const ProfileVisibility = IDL.Variant({
  'ConnectionsOnly' : IDL.Null,
  'Public' : IDL.Null,
});
export const EducationEntry = IDL.Record({
  'field' : IDL.Text,
  'school' : IDL.Text,
  'year' : IDL.Text,
  'degree' : IDL.Text,
});
export const WorkEntry = IDL.Record({
  'startYear' : IDL.Text,
  'title' : IDL.Text,
  'endYear' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'resume' : IDL.Opt(ExternalBlob),
  'profileVisibility' : ProfileVisibility,
  'headline' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'education' : IDL.Vec(EducationEntry),
  'workHistory' : IDL.Vec(WorkEntry),
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'industry' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addEndorsement' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'applyToJob' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func([IDL.Nat, IDL.Text, PostType], [IDL.Nat], []),
  'deactivateJob' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(PostComment)], ['query']),
  'getConnectionRequests' : IDL.Func([], [IDL.Vec(ConnRequest)], ['query']),
  'getConnectionSuggestions' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'getConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationPreview)], ['query']),
  'getEndorsements' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Endorsement)],
      ['query'],
    ),
  'getFeedPosts' : IDL.Func([IDL.Nat], [IDL.Vec(GroupPost)], ['query']),
  'getGroupPosts' : IDL.Func([IDL.Nat], [IDL.Vec(GroupPost)], ['query']),
  'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosting)], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getMyJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getPublicProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getSentRequests' : IDL.Func([], [IDL.Vec(ConnRequest)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadNotificationsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Nat], [], []),
  'leaveGroup' : IDL.Func([IDL.Nat], [], []),
  'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'removeConnection' : IDL.Func([IDL.Principal], [], []),
  'respondToRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'searchJobs' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(JobPosting)],
      ['query'],
    ),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserSummary)], ['query']),
  'sendConnectionRequest' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'setAvatar' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'setProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(WorkEntry),
        IDL.Vec(EducationEntry),
      ],
      [],
      [],
    ),
  'setResume' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'toggleLike' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updatePrivacySettings' : IDL.Func([ProfileVisibility], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostType = IDL.Variant({
    'Question' : IDL.Null,
    'Article' : IDL.Null,
    'Insight' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'Applied' : IDL.Null,
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
  });
  const JobApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'resume' : IDL.Opt(ExternalBlob),
    'applicantPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
  });
  const PostComment = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorPrincipal' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  const ConnStatus = IDL.Variant({
    'Accepted' : IDL.Null,
    'Declined' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ConnRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : ConnStatus,
    'from' : IDL.Principal,
    'createdAt' : IDL.Int,
  });
  const UserSummary = IDL.Record({
    'principal' : IDL.Principal,
    'headline' : IDL.Text,
    'name' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const ConversationPreview = IDL.Record({
    'lastMessageAt' : IDL.Int,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
    'partner' : IDL.Principal,
  });
  const Endorsement = IDL.Record({
    'createdAt' : IDL.Int,
    'skill' : IDL.Text,
    'endorserPrincipal' : IDL.Principal,
  });
  const GroupPost = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'likeCount' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'groupId' : IDL.Nat,
    'authorPrincipal' : IDL.Principal,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'creatorPrincipal' : IDL.Principal,
    'industry' : IDL.Text,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'experienceLevel' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requirements' : IDL.Text,
    'posterPrincipal' : IDL.Principal,
    'location' : IDL.Text,
    'industry' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'body' : IDL.Text,
    'from' : IDL.Principal,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'attachmentName' : IDL.Opt(IDL.Text),
    'attachment' : IDL.Opt(ExternalBlob),
  });
  const NotifKind = IDL.Variant({
    'PostCommented' : IDL.Null,
    'ConnectionAccepted' : IDL.Null,
    'JobApplicationReceived' : IDL.Null,
    'SkillEndorsed' : IDL.Null,
    'ConnectionRequest' : IDL.Null,
    'NewMessage' : IDL.Null,
    'PostLiked' : IDL.Null,
    'GroupPostCreated' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'kind' : NotifKind,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'referenceId' : IDL.Nat,
    'message' : IDL.Text,
    'recipientPrincipal' : IDL.Principal,
  });
  const ProfileVisibility = IDL.Variant({
    'ConnectionsOnly' : IDL.Null,
    'Public' : IDL.Null,
  });
  const EducationEntry = IDL.Record({
    'field' : IDL.Text,
    'school' : IDL.Text,
    'year' : IDL.Text,
    'degree' : IDL.Text,
  });
  const WorkEntry = IDL.Record({
    'startYear' : IDL.Text,
    'title' : IDL.Text,
    'endYear' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'resume' : IDL.Opt(ExternalBlob),
    'profileVisibility' : ProfileVisibility,
    'headline' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'education' : IDL.Vec(EducationEntry),
    'workHistory' : IDL.Vec(WorkEntry),
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'industry' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addEndorsement' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'applyToJob' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func([IDL.Nat, IDL.Text, PostType], [IDL.Nat], []),
    'deactivateJob' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(PostComment)], ['query']),
    'getConnectionRequests' : IDL.Func([], [IDL.Vec(ConnRequest)], ['query']),
    'getConnectionSuggestions' : IDL.Func(
        [],
        [IDL.Vec(UserSummary)],
        ['query'],
      ),
    'getConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPreview)],
        ['query'],
      ),
    'getEndorsements' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Endorsement)],
        ['query'],
      ),
    'getFeedPosts' : IDL.Func([IDL.Nat], [IDL.Vec(GroupPost)], ['query']),
    'getGroupPosts' : IDL.Func([IDL.Nat], [IDL.Vec(GroupPost)], ['query']),
    'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosting)], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getMyJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Profile)],
        ['query'],
      ),
    'getSentRequests' : IDL.Func([], [IDL.Vec(ConnRequest)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadNotificationsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Nat], [], []),
    'leaveGroup' : IDL.Func([IDL.Nat], [], []),
    'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'removeConnection' : IDL.Func([IDL.Principal], [], []),
    'respondToRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'searchJobs' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserSummary)], ['query']),
    'sendConnectionRequest' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'setAvatar' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'setProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(WorkEntry),
          IDL.Vec(EducationEntry),
        ],
        [],
        [],
      ),
    'setResume' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'toggleLike' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updatePrivacySettings' : IDL.Func([ProfileVisibility], [], []),
  });
};

export const init = ({ IDL }) => { return []; };