/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WorkEntry {
    startYear: string;
    title: string;
    endYear: string;
    description: string;
    company: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Profile {
    bio: string;
    resume?: ExternalBlob;
    profileVisibility: ProfileVisibility;
    headline: string;
    name: string;
    createdAt: bigint;
    education: Array<EducationEntry>;
    workHistory: Array<WorkEntry>;
    skills: Array<string>;
    location: string;
    industry: string;
    avatar?: ExternalBlob;
}
export interface JobPosting {
    id: bigint;
    experienceLevel: string;
    title: string;
    active: boolean;
    createdAt: bigint;
    description: string;
    company: string;
    salaryRange: string;
    requirements: string;
    posterPrincipal: Principal;
    location: string;
    industry: string;
}
export interface JobApplication {
    id: bigint;
    status: ApplicationStatus;
    resume?: ExternalBlob;
    applicantPrincipal: Principal;
    createdAt: bigint;
    jobId: bigint;
    coverLetter: string;
}
export interface Group {
    id: bigint;
    name: string;
    createdAt: bigint;
    memberCount: bigint;
    description: string;
    creatorPrincipal: Principal;
    industry: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Endorsement {
    createdAt: bigint;
    skill: string;
    endorserPrincipal: Principal;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface EducationEntry {
    field: string;
    school: string;
    year: string;
    degree: string;
}
export interface ConversationPreview {
    lastMessageAt: bigint;
    lastMessage: string;
    unreadCount: bigint;
    partner: Principal;
}
export interface UserSummary {
    principal: Principal;
    headline: string;
    name: string;
    avatar?: ExternalBlob;
}
export interface Message {
    id: bigint;
    to: Principal;
    body: string;
    from: Principal;
    createdAt: bigint;
    read: boolean;
    attachmentName?: string;
    attachment?: ExternalBlob;
}
export interface PostComment {
    id: bigint;
    body: string;
    createdAt: bigint;
    authorPrincipal: Principal;
    postId: bigint;
}
export interface Notification {
    id: bigint;
    kind: NotifKind;
    createdAt: bigint;
    read: boolean;
    referenceId: bigint;
    message: string;
    recipientPrincipal: Principal;
}
export interface GroupPost {
    id: bigint;
    postType: PostType;
    likeCount: bigint;
    body: string;
    createdAt: bigint;
    groupId: bigint;
    authorPrincipal: Principal;
}
export interface ConnRequest {
    id: bigint;
    to: Principal;
    status: ConnStatus;
    from: Principal;
    createdAt: bigint;
}
export enum ApplicationStatus {
    Applied = "Applied",
    Rejected = "Rejected",
    Accepted = "Accepted"
}
export enum ConnStatus {
    Accepted = "Accepted",
    Declined = "Declined",
    Pending = "Pending"
}
export enum NotifKind {
    PostCommented = "PostCommented",
    ConnectionAccepted = "ConnectionAccepted",
    JobApplicationReceived = "JobApplicationReceived",
    SkillEndorsed = "SkillEndorsed",
    ConnectionRequest = "ConnectionRequest",
    NewMessage = "NewMessage",
    PostLiked = "PostLiked",
    GroupPostCreated = "GroupPostCreated"
}
export enum PostType {
    Question = "Question",
    Article = "Article",
    Insight = "Insight"
}
export enum ProfileVisibility {
    ConnectionsOnly = "ConnectionsOnly",
    Public = "Public"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addComment(postId: bigint, body: string): Promise<bigint>;
    addEndorsement(target: Principal, skill: string): Promise<void>;
    applyToJob(jobId: bigint, coverLetter: string, resume: ExternalBlob | null): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(target: Principal): Promise<void>;
    createGroup(name: string, description: string, industry: string): Promise<bigint>;
    createJob(title: string, company: string, description: string, requirements: string, salaryRange: string, location: string, industry: string, experienceLevel: string): Promise<bigint>;
    createPost(groupId: bigint, body: string, postType: PostType): Promise<bigint>;
    deactivateJob(id: bigint): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    getApplicationsForJob(jobId: bigint): Promise<Array<JobApplication>>;
    getBlockedUsers(): Promise<Array<Principal>>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(postId: bigint): Promise<Array<PostComment>>;
    getConnectionRequests(): Promise<Array<ConnRequest>>;
    getConnectionSuggestions(): Promise<Array<UserSummary>>;
    getConnections(): Promise<Array<Principal>>;
    getConversations(): Promise<Array<ConversationPreview>>;
    getEndorsements(target: Principal): Promise<Array<Endorsement>>;
    getFeedPosts(limit: bigint): Promise<Array<GroupPost>>;
    getGroupPosts(groupId: bigint): Promise<Array<GroupPost>>;
    getGroups(): Promise<Array<Group>>;
    getJob(id: bigint): Promise<JobPosting | null>;
    getMessages(partner: Principal): Promise<Array<Message>>;
    getMyApplications(): Promise<Array<JobApplication>>;
    getMyGroups(): Promise<Array<Group>>;
    getMyJobs(): Promise<Array<JobPosting>>;
    getNotifications(): Promise<Array<Notification>>;
    getProfile(): Promise<Profile | null>;
    getPublicProfile(target: Principal): Promise<Profile | null>;
    getSentRequests(): Promise<Array<ConnRequest>>;
    getUnreadCount(): Promise<bigint>;
    getUnreadNotificationsCount(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    joinGroup(groupId: bigint): Promise<void>;
    leaveGroup(groupId: bigint): Promise<void>;
    markMessagesRead(partner: Principal): Promise<void>;
    markNotificationsRead(): Promise<void>;
    removeConnection(other: Principal): Promise<void>;
    respondToRequest(requestId: bigint, accept: boolean): Promise<void>;
    searchJobs(keyword: string, location: string, industry: string, experienceLevel: string): Promise<Array<JobPosting>>;
    searchUsers(keyword: string): Promise<Array<UserSummary>>;
    sendConnectionRequest(to: Principal): Promise<bigint>;
    sendMessage(to: Principal, body: string, attachment: ExternalBlob | null, attachmentName: string | null): Promise<bigint>;
    setAvatar(avatar: ExternalBlob | null): Promise<void>;
    setProfile(name: string, headline: string, location: string, industry: string, bio: string, skills: Array<string>, workHistory: Array<WorkEntry>, education: Array<EducationEntry>): Promise<void>;
    setResume(resume: ExternalBlob | null): Promise<void>;
    toggleLike(postId: bigint): Promise<boolean>;
    unblockUser(target: Principal): Promise<void>;
    updateApplicationStatus(applicationId: bigint, status: ApplicationStatus): Promise<void>;
    updateJob(id: bigint, title: string, company: string, description: string, requirements: string, salaryRange: string, location: string, industry: string, experienceLevel: string): Promise<void>;
    updatePrivacySettings(visibility: ProfileVisibility): Promise<void>;
}
import type { ApplicationStatus as _ApplicationStatus, ConnRequest as _ConnRequest, ConnStatus as _ConnStatus, EducationEntry as _EducationEntry, Error as _Error, ExternalBlob as _ExternalBlob, GroupPost as _GroupPost, JobApplication as _JobApplication, JobPosting as _JobPosting, Message as _Message, NotifKind as _NotifKind, Notification as _Notification, PostType as _PostType, Profile as _Profile, ProfileVisibility as _ProfileVisibility, Result as _Result, UserRole as _UserRole, UserSummary as _UserSummary, WorkEntry as _WorkEntry, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addEndorsement(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEndorsement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEndorsement(arg0, arg1);
            return result;
        }
    }
    async applyToJob(arg0: bigint, arg1: string, arg2: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1, arg2);
            return result;
        }
    }
    async createJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createPost(arg0: bigint, arg1: string, arg2: PostType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, to_candid_PostType_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, to_candid_PostType_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deactivateJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateJob(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async getApplicationsForJob(arg0: bigint): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForJob(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForJob(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: bigint): Promise<Array<PostComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getConnectionRequests(): Promise<Array<ConnRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectionRequests();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectionRequests();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnectionSuggestions(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectionSuggestions();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectionSuggestions();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnections(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnections();
            return result;
        }
    }
    async getConversations(): Promise<Array<ConversationPreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getEndorsements(arg0: Principal): Promise<Array<Endorsement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEndorsements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEndorsements(arg0);
            return result;
        }
    }
    async getFeedPosts(arg0: bigint): Promise<Array<GroupPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedPosts(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedPosts(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupPosts(arg0: bigint): Promise<Array<GroupPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupPosts(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupPosts(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroups();
            return result;
        }
    }
    async getJob(arg0: bigint): Promise<JobPosting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGroups();
            return result;
        }
    }
    async getMyJobs(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyJobs();
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSentRequests(): Promise<Array<ConnRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentRequests();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentRequests();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUnreadNotificationsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationsCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGroup(arg0);
            return result;
        }
    }
    async leaveGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async markMessagesRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async removeConnection(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeConnection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeConnection(arg0);
            return result;
        }
    }
    async respondToRequest(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToRequest(arg0, arg1);
            return result;
        }
    }
    async searchJobs(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendConnectionRequest(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendConnectionRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendConnectionRequest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: ExternalBlob | null, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async setAvatar(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAvatar(await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAvatar(await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: Array<WorkEntry>, arg7: Array<EducationEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async setResume(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setResume(await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setResume(await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleLike(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateJob(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updatePrivacySettings(arg0: ProfileVisibility): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrivacySettings(to_candid_ProfileVisibility_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrivacySettings(to_candid_ProfileVisibility_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ConnRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnRequest): ConnRequest {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ConnStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnStatus): ConnStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GroupPost_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupPost): GroupPost {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_JobApplication_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobApplication): Promise<JobApplication> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Message_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Promise<Message> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_NotifKind_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotifKind): NotifKind {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_PostType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostType): PostType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileVisibility_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileVisibility): ProfileVisibility {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_Profile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Promise<Profile> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_UserSummary_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): Promise<UserSummary> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobPosting]): JobPosting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Promise<Profile | null> {
    return value.length === 0 ? null : await from_candid_Profile_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    resume: [] | [_ExternalBlob];
    applicantPrincipal: Principal;
    createdAt: bigint;
    jobId: bigint;
    coverLetter: string;
}): Promise<{
    id: bigint;
    status: ApplicationStatus;
    resume?: ExternalBlob;
    applicantPrincipal: Principal;
    createdAt: bigint;
    jobId: bigint;
    coverLetter: string;
}> {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n21(_uploadFile, _downloadFile, value.status),
        resume: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.resume)),
        applicantPrincipal: value.applicantPrincipal,
        createdAt: value.createdAt,
        jobId: value.jobId,
        coverLetter: value.coverLetter
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: Principal;
    status: _ConnStatus;
    from: Principal;
    createdAt: bigint;
}): {
    id: bigint;
    to: Principal;
    status: ConnStatus;
    from: Principal;
    createdAt: bigint;
} {
    return {
        id: value.id,
        to: value.to,
        status: from_candid_ConnStatus_n30(_uploadFile, _downloadFile, value.status),
        from: value.from,
        createdAt: value.createdAt
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    headline: string;
    name: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    principal: Principal;
    headline: string;
    name: string;
    avatar?: ExternalBlob;
}> {
    return {
        principal: value.principal,
        headline: value.headline,
        name: value.name,
        avatar: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postType: _PostType;
    likeCount: bigint;
    body: string;
    createdAt: bigint;
    groupId: bigint;
    authorPrincipal: Principal;
}): {
    id: bigint;
    postType: PostType;
    likeCount: bigint;
    body: string;
    createdAt: bigint;
    groupId: bigint;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        postType: from_candid_PostType_n38(_uploadFile, _downloadFile, value.postType),
        likeCount: value.likeCount,
        body: value.body,
        createdAt: value.createdAt,
        groupId: value.groupId,
        authorPrincipal: value.authorPrincipal
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: Principal;
    body: string;
    from: Principal;
    createdAt: bigint;
    read: boolean;
    attachmentName: [] | [string];
    attachment: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    to: Principal;
    body: string;
    from: Principal;
    createdAt: bigint;
    read: boolean;
    attachmentName?: string;
    attachment?: ExternalBlob;
}> {
    return {
        id: value.id,
        to: value.to,
        body: value.body,
        from: value.from,
        createdAt: value.createdAt,
        read: value.read,
        attachmentName: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.attachmentName)),
        attachment: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.attachment))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _NotifKind;
    createdAt: bigint;
    read: boolean;
    referenceId: bigint;
    message: string;
    recipientPrincipal: Principal;
}): {
    id: bigint;
    kind: NotifKind;
    createdAt: bigint;
    read: boolean;
    referenceId: bigint;
    message: string;
    recipientPrincipal: Principal;
} {
    return {
        id: value.id,
        kind: from_candid_NotifKind_n48(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        read: value.read,
        referenceId: value.referenceId,
        message: value.message,
        recipientPrincipal: value.recipientPrincipal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    resume: [] | [_ExternalBlob];
    profileVisibility: _ProfileVisibility;
    headline: string;
    name: string;
    createdAt: bigint;
    education: Array<_EducationEntry>;
    workHistory: Array<_WorkEntry>;
    skills: Array<string>;
    location: string;
    industry: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    resume?: ExternalBlob;
    profileVisibility: ProfileVisibility;
    headline: string;
    name: string;
    createdAt: bigint;
    education: Array<EducationEntry>;
    workHistory: Array<WorkEntry>;
    skills: Array<string>;
    location: string;
    industry: string;
    avatar?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        resume: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.resume)),
        profileVisibility: from_candid_ProfileVisibility_n53(_uploadFile, _downloadFile, value.profileVisibility),
        headline: value.headline,
        name: value.name,
        createdAt: value.createdAt,
        education: value.education,
        workHistory: value.workHistory,
        skills: value.skills,
        location: value.location,
        industry: value.industry,
        avatar: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Applied: null;
} | {
    Rejected: null;
} | {
    Accepted: null;
}): ApplicationStatus {
    return "Applied" in value ? ApplicationStatus.Applied : "Rejected" in value ? ApplicationStatus.Rejected : "Accepted" in value ? ApplicationStatus.Accepted : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Accepted: null;
} | {
    Declined: null;
} | {
    Pending: null;
}): ConnStatus {
    return "Accepted" in value ? ConnStatus.Accepted : "Declined" in value ? ConnStatus.Declined : "Pending" in value ? ConnStatus.Pending : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Question: null;
} | {
    Article: null;
} | {
    Insight: null;
}): PostType {
    return "Question" in value ? PostType.Question : "Article" in value ? PostType.Article : "Insight" in value ? PostType.Insight : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PostCommented: null;
} | {
    ConnectionAccepted: null;
} | {
    JobApplicationReceived: null;
} | {
    SkillEndorsed: null;
} | {
    ConnectionRequest: null;
} | {
    NewMessage: null;
} | {
    PostLiked: null;
} | {
    GroupPostCreated: null;
}): NotifKind {
    return "PostCommented" in value ? NotifKind.PostCommented : "ConnectionAccepted" in value ? NotifKind.ConnectionAccepted : "JobApplicationReceived" in value ? NotifKind.JobApplicationReceived : "SkillEndorsed" in value ? NotifKind.SkillEndorsed : "ConnectionRequest" in value ? NotifKind.ConnectionRequest : "NewMessage" in value ? NotifKind.NewMessage : "PostLiked" in value ? NotifKind.PostLiked : "GroupPostCreated" in value ? NotifKind.GroupPostCreated : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ConnectionsOnly: null;
} | {
    Public: null;
}): ProfileVisibility {
    return "ConnectionsOnly" in value ? ProfileVisibility.ConnectionsOnly : "Public" in value ? ProfileVisibility.Public : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobApplication>): Promise<Array<JobApplication>> {
    return await Promise.all(value.map(async (x)=>await from_candid_JobApplication_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConnRequest>): Array<ConnRequest> {
    return value.map((x)=>from_candid_ConnRequest_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserSummary>): Promise<Array<UserSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserSummary_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupPost>): Array<GroupPost> {
    return value.map((x)=>from_candid_GroupPost_n36(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Promise<Array<Message>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Message_n42(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n46(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PostType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): _PostType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileVisibility_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileVisibility): _ProfileVisibility {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): {
    Question: null;
} | {
    Article: null;
} | {
    Insight: null;
} {
    return value == PostType.Question ? {
        Question: null
    } : value == PostType.Article ? {
        Article: null
    } : value == PostType.Insight ? {
        Insight: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    Applied: null;
} | {
    Rejected: null;
} | {
    Accepted: null;
} {
    return value == ApplicationStatus.Applied ? {
        Applied: null
    } : value == ApplicationStatus.Rejected ? {
        Rejected: null
    } : value == ApplicationStatus.Accepted ? {
        Accepted: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileVisibility): {
    ConnectionsOnly: null;
} | {
    Public: null;
} {
    return value == ProfileVisibility.ConnectionsOnly ? {
        ConnectionsOnly: null
    } : value == ProfileVisibility.Public ? {
        Public: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
